# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "rekognify"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "rekognify"
region = "eu-west-2"
disable_rollback = false

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
image_repositories = [
    "ImageInfoHandler=626635403708.dkr.ecr.eu-west-2.amazonaws.com/rekognifye82d090a/imageinfohandler4ef8188crepo",
    "ImageUploadHandler=626635403708.dkr.ecr.eu-west-2.amazonaws.com/rekognifye82d090a/imageuploadhandlera77b1b71repo",
    "S3SignedUrlHandler=626635403708.dkr.ecr.eu-west-2.amazonaws.com/rekognifye82d090a/s3signedurlhandler1645e90brepo"
]

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
